### ISSUE TITLE
Product single page: Product gallery images are no longer displayed.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Southside-Pool-Service#112]

**Comment by Rahul-titan** [comment]
There is one change to the design which needs to take place in IMP - it is on the 'Products Singles' page: the 3 x smaller images underneath the main image need to be removed. Please refer to the attachment. 
https://projects.titanweb.com.au/public/index.php?path_info=projects%2Fsouthside-pool-services-pack1responsive-%2Ftasks%2F8%2Fcomments%2F66856%2Fattachments%2F31947%2Fdownload
Thank you

**Comment by roseliesromeo** [comment]
We'll mark this as won't fix since there is change in implementation while still in QA.
Refer to this change in AC: https://projects.titanweb.com.au/public/index.php?path_info=projects%2Fsouthside-pool-services-pack1responsive-%2Ftasks%2F8
