### ISSUE TITLE
Inner pages: There is no need to add acf for the page title.  Page title at back end should be utilized.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Southside-Pool-Service#66]
![image](https://cloud.githubusercontent.com/assets/11186313/11086499/af787dc2-888c-11e5-86a8-f33493d239e1.png)

**Comment by Rahul-titan** [comment]
As per design, Breadcrumbs are there. To maintain breadcrumbs, we used page-title remain same
and for page-title, we used sub-titles (acf).

**Comment by roseliesromeo** [comment]
We can maintain the breadcrumbs while using page title as the H1. No acf needed.
Please refer to this site.
http://adventure4x4.stage.titanweb.com.au/news/
http://adventure4x4.stage.titanweb.com.au/news-11/

**Comment by roseliesromeo** [comment]
Not fixed for Testimonials and News page.
![image](https://cloud.githubusercontent.com/assets/11186313/11262024/1b9b4e3e-8eb5-11e5-99fe-680873fd41fe.png)

**Comment by roseliesromeo** [comment]
Not fixed for News page.
![image](https://cloud.githubusercontent.com/assets/11186313/11521735/4fee4e4a-98ea-11e5-9b4e-9b0857e18e3c.png)

**Comment by roseliesromeo** [comment]
![image](https://cloud.githubusercontent.com/assets/11186313/11645615/f55280b8-9d90-11e5-8ec6-996814a02ce4.png)

**Comment by roseliesromeo** [comment]
Page h1 should utilize the page title just like you did to the testimonial (What our clients <span>Have to say</span>) page.
![image](https://cloud.githubusercontent.com/assets/11186313/11709329/9f9c19f0-9f51-11e5-8f12-2a2c9110a1dc.png)

**Comment by roseliesromeo** [comment]
@saif-titan 
Page H1 should read <b>"Wha'ts been happening" and not 'News'
Are you sure you are getting what the issue?
Please this simple issue has been on for how many rounds already.
