### ISSUE TITLE
Product category page: Bullet marks aren't styled similarly as the rest of the pages.  

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Southside-Pool-Service#80]
![image](https://cloud.githubusercontent.com/assets/11186313/11088416/16771c26-889d-11e5-8e8e-e3d65003c426.png)

**Comment by roseliesromeo** [comment]
You just removed the category.  Issue is not fixed.
http://southside-poolservices.stage.titanweb.com.au/product-category/category-name-1/subcategory-title-goes-here-for-two-lines-long/

**Comment by Rahul-titan** [comment]
Please treat it as enhancement, by default the category description box unable to convert given content into HTML tags.

**Comment by roseliesromeo** [comment]
Please refer to this site.  Subcategory page content can be styled similarly as the parent category page.
http://paradisepools.stage.titanweb.com.au/product-category/subcategory-title-goes-here-for-two-lines-long/
