### ISSUE TITLE
Product single page: Product thumbnails won't open in a fancy box but in a new tab.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Southside-Pool-Service#84]
![image](https://cloud.githubusercontent.com/assets/11186313/11088712/436ddd12-889f-11e5-9896-a5fea227f59e.png)

**Comment by roseliesromeo** [comment]
We'll verify once bug #112 is fixed.

**Comment by Rahul-titan** [comment]
There is one change to the design which needs to take place in IMP - it is on the 'Products Singles' page: the 3 x smaller images underneath the main image need to be removed. Please refer to the attachment.
https://projects.titanweb.com.au/public/index.php?path_info=projects%2Fsouthside-pool-services-pack1responsive-%2Ftasks%2F8%2Fcomments%2F66856%2Fattachments%2F31947%2Fdownload
Thank you

**Comment by roseliesromeo** [comment]
Marked as won't fix as there is an update in the implementation while in QA.
Refer to this amend: https://projects.titanweb.com.au/public/index.php?path_info=projects%2Fsouthside-pool-services-pack1responsive-%2Ftasks%2F8
